[package]
name = "wof-cli"
version = "0.1.0"
authors = ["Jones Magloire @Joxit"]
description = "The Who's On First command line aggregator."
edition = "2018"
license = "MIT"
autobins = false

[[bin]]
name = "wof"
path = "src/main.rs"

[dependencies]
structopt = "0.3"
which = "3.1.0"
serde_json = "1.0"
git2 = "0.10"
tar = "0.4.26"
flate2 = "1.0.13"
attohttpc = "0.8.0"
