name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Build with CLI feature
      run: cargo build --features cli --verbose
    - name: Build with GDAL feature
      run: cargo build --features with-gdal --verbose
    - name: Run tests
      run: cargo test --verbose
