name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Build with CLI feature
      run: cargo build --features cli --verbose
    - name: Run tests
      run: cargo test --verbose
