name: Rust

on:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Build with CLI feature
      run: cargo build --features cli --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Publish
      if: success() && github.event_name == 'release'
      env:
        CRATE_IO_ACCESS_TOKEN: ${{ secrets.CRATE_IO_ACCESS_TOKEN }}
      run: cargo publish --token $CRATE_IO_ACCESS_TOKEN